### PR TITLE
Added content type negotiation using headers

### PR DESCRIPTION
**Pull request by aaronhaines**
Implemented the same way as method negotiation. Not sure if the default accept type should be 'html' or 'view' or something else.
Specifying the accept-type as HTML would seem to imply that the resource should respond with an HTML representation. As views are free to respond or not, maybe this is misleading..

### CODE REVIEW

**Comment by aaronhaines** [comment]
Updating this to use generic 'negotiate on comparator'

**Comment by mstade** [comment]
For the default accept type(s) clients generally pick a set of defaults that make sense to them. Here's what Chrome sets as the default accept header:

```
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
```

It prefers html over anything, but will accept everything. Some formats are rendered (HTML, WebP, XML, videos, etc.) and others are just rendered as plain text. The question of what to accept really comes down to what's going to happen with the result; browsers render it to screen, what should nap do? Turn JSON into JavaScript objects? HTML into DOM? A representation can be represented in different ways in different contexts – I'm pretty sure buddha said this at some point. :o)

I think as a default, it might make sense to just return a string in the body of a response. There's an obvious future compatibility problem with this though, because if you start of with just returning a string for `text/html`, and then later decide that the response body should be DOM, it'll break clients that depend on the old behavior. There's probably some clever design to alleviate this, but I can't immediately think of one.

Btw, the correct HTTP response code for unsupported media types is 415 – not sure if this matters. I'm also not sure if it matters, but the accept header semantics are a bit more complex than can be implemented with simple string comparisons. `text/*` for instance would match anything under the `text` tree, and the `q` parameter is essentially a way to order the importance of media types. Again, not sure if this matters.

**Comment by aaronhaines** [comment]
For future compatibility the client can check the content-type of the response, but there is always the possibility of future breaking changes with any assumed default.
After some discussion today the plan is that 'Views' will return a function which can be invoked on a dom node - i.e. the body of the response would be the function.
Open to suggestions of what the media type should be.  nap/view, nap/component, javascript/function ?

As to the default, I don't know if text/html makes sense in this context. My guess is that most of the time the response will either be json or a view function

**Comment by mstade** [comment]
> 'Views' will return a function which can be invoked on a dom node - i.e. the body of the response would be the function.

Sir, if I may be so bold – I think this is damn beautiful! It'd mean the function could be anything – jQuery, D3, plain ol' JS – so long as the signature is compatible. Brilliant abstraction!

> Open to suggestions of what the media type should be. nap/view, nap/component, javascript/function ?

I'd say it depends on how conventional you want to be. I reckon – because I'm anal-retentive that way – that if the media type pattern should be used, then it should probably also follow [IANA recommendations](http://tools.ietf.org/html/rfc6838#section-3). In that case, it ought to be `application/x.nap.view` or some such for experimental stuff and if later the type should be registered then the vendor tree is probably appropriate; e.g. `application/vnd.nap.view`.

> As to the default, I don't know if text/html makes sense in this context. My guess is that most of the time the response will either be json or a view function.

It can be more than one type. Like I mentioned, browsers generally don't just accept `text/html`, but a wide array of types – even `*/*`! I don't think nap has to be very different; the context suggests that `text/html`, `application/json` and `application/x.nap.view` (or whatever) can be singled out because their body representations can be made into something meaningful (DOM, JS object, and view function respectively.) But the default accept could just as well include `*/*` in which case nap probably shouldn't process the body at all, just pass along whatever data is in the body. (In this case, consider turning the body into a string representation, so mutable state isn't passed around.)

Does this make sense?

**Comment by sammyt** [comment]
> Does this make sense?

Yes :) merging this now, will open new issues for the further enhancements mentioned above.

**Pull request merged**
