### PR TITLE
Exposing nap.uri

### PR DESCRIPTION
**Pull request by grancalavera**
We are creating this API because in some cases we need to be able to interpolate patterns independently of the existing resources.

### CODE REVIEW

**Comment by mstade** [comment]
Hey @grancalavera, could you explain the use case a bit further?

**Comment by grancalavera** [comment]
Given you have a `params` object and a `ptn` uri pattern, with this change you can render a new uri independently of any existing web:

```
var myUri = nap.uri(aPattern, someParams)
```

There is some noise in the pull request generated by whitespace changes, which I can remove if necessary. Besides that, the main change consists in extracting `web.uri` to allow using `uri` when there is not a reference to a `web` available.

In our application, `web` is an internal detail, and can't be accessed using a public API. In some cases, we need to render uri patterns, and we want to ensure the same API is used everywhere an uri pattern needs to be rendered. As such, we want to expose nap's `uri` directly.

**Comment by mstade** [comment]
I have a gut feeling that this shouldn't actually be a feature that's part of nap, but touches on a larger discussion of nap and its responsibilities and whether or not some things should be broken out in to other modules. In the interest of progress I'll merge this once #22 is merged, not least of all since it's already in use.

**Comment by grancalavera** [comment]
I've been thinking the same myself. Should this be part of thumb?

**Comment by mstade** [comment]
Maybe, but actually I think rhumb is overreaching in its remit as well. I opened up an issue there about URI templates, which is probably related here. Feel free to look at it (sorry, on the phone now so can't look up the link) and comment. When I'm on my laptop again I'll write something a bit more reasoned. :o)

**Comment by mstade** [comment]
This issue was moved to websdk/nap#11

**Pull request closed without merging**
